apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cron
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: main
            image: {{ .Values.image }}
            command:
              {{- range .Values.command }}
            - {{ . }}
              {{- end }}
          restartPolicy: OnFailure
