apiVersion: acme.com/v1
kind: Repository
metadata:
  name: my-repo
name: my-unique-repo
owner: monadaco
files:
  - path: .github/workflows/build.yaml
    content: |
      name: GitHub Actions Demo
      on: [push]
      jobs:
        build:
          runs-on: ubuntu-latest
          steps:
            - run: echo "Building the service"