apiVersion: v2
name: postgres
description: Postgres database for Acme teams
type: application
version: 0.1.0
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.5.20
